Update setup_sql.yml

diff --git a/.github/workflows/setup_sql.yml b/.github/workflows/setup_sql.yml
--- a/.github/workflows/setup_sql.yml
+++ b/.github/workflows/setup_sql.yml
@@ -57,7 +57,7 @@ jobs:
 
         run: |
 
-          /opt/mssql-tools/bin/sqlcmd -S "$SQL_SERVER,$SQL_PORT" -U "$SQL_USER" -P "$SQL_PASSWORD" -i scripts/setup1.sql -o output.log -x || echo "sqlcmd failed, check output.log"
+          /opt/mssql-tools/bin/sqlcmd -S "$SQL_SERVER,$SQL_PORT" -U "$SQL_USER" -P "$SQL_PASSWORD" -i scripts/setup.sql -o output.log -x || echo "sqlcmd failed, check output.log"
 
           cat output.log
  
@@ -111,7 +111,7 @@ jobs:
 
         run: |
 
-          /opt/mssql-tools/bin/sqlcmd -S "$SQL_SERVER,$SQL_PORT" -U "$SQL_USER" -P "$SQL_PASSWORD" -i scripts/setup1.sql -o output.log -x || echo "sqlcmd failed, check output.log"
+          /opt/mssql-tools/bin/sqlcmd -S "$SQL_SERVER,$SQL_PORT" -U "$SQL_USER" -P "$SQL_PASSWORD" -i scripts/setup.sql -o output.log -x || echo "sqlcmd failed, check output.log"
 
           cat output.log
 
